repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.14.9"
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-illegal-windows-names
      - id: mixed-line-ending
  - repo: local #run custom scripts from own repo
    hooks:
      - id: lint-staged-webapp
        name: Run lint-staged on webapp staged files
        entry: bash run-lint-staged-if-webapp.sh
        language: system
        pass_filenames: false # This hook handles filenames internally